### ISSUE TITLE
Issue after cloning project (tutorial)

### ISSUE THREAD

**Issue by tmoore42six** [planetoftheweb/responsivebootstrap#1]
I am doing the Up and Running with Git tutorial on Lydia.com. When I cloned angulardata everything went fine. When I cloned this project, I can not get the project to run correctly. I have done it 4 times with the same result.  I have attached a file of what the project looks like every time, and a file of my terminal for you to check out.
The only issue I see is "HTML Warning: Failed to run validation on index.html"

![screen shot 2015-12-09 at 2 33 34 pm](https://cloud.githubusercontent.com/assets/16230002/11696359/dc13294e-9e81-11e5-8eaa-73e030780be5.png)

[terminal.txt](https://github.com/planetoftheweb/responsivebootstrap/files/57261/terminal.txt)

**Comment by tmoore42six** [comment]
Note: When I continued in the project and checked out 02_01, everything works fine. So Just noting that master didnt work correctly for me.

**Comment by Jay-TechSalon** [comment]
If you would of scrolled down, there is content below. The big white area is a div container which has a height set for the image that would normally belong in this project. Since it is not there, looks like a broken file. -- I had same thing happen and scrolled and noticed it is just the images... also read me file says there will be no images to work with.. big hint for me.

**Comment by Ingvar-V** [comment]
Dear Mr.Villalobos,

Thank you very much for the great tutorial.
Could you be so kind to help me with the one issue, please?
If I click a menu item (for example, Testimonials) and after that move the mouse cursor to another item (e.g. Services) I can see that the Testimonials menu item has the light gray background instead of brown. Is it possible to fix this issue?

Thank you in advance.
Kind regards,
Igor.
![screenshot](https://cloud.githubusercontent.com/assets/23147367/25497280/bbb1e458-2b8c-11e7-8a79-11671e6f9f63.jpg)

**Comment by planetoftheweb** [comment]
If you watch the exercise files video, it mentions that you need to download the images folder separately from the site.
